#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sun Oct 15 15:45:14 2017

@author: sahiljain
"""

import os 
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np  
import statsmodels.api as sm
import statsmodels.formula.api as smf 
from scipy.stats import t as tdist 
from statsmodels.stats.outliers_influence import summary_table
get_ipython().magic(u'matplotlib inline')
from statsmodels.sandbox.regression.predstd import wls_prediction_std as pi

os.getcwd()